file added

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -16,9 +16,17 @@ jobs:
     steps:
       - checkout
       - run:
+          name: Install Python, pip, jq, and awscli
+          command: |
+            sudo apt-get update
+            sudo apt-get install -y python3 python3-pip jq awscli
+      - run:
           name: Assume AWS OIDC Role
           command: |
             ROLE_ARN="arn:aws:iam::961341535277:role/circleci"
+            if [ ! -f /tmp/circleci_oidc_token ]; then
+              echo "OIDC token file not found! Make sure 'oidc: true' is set under this job in your workflow." && exit 1
+            fi
             OIDC_TOKEN=$(cat /tmp/circleci_oidc_token)
             CREDS_JSON=$(aws sts assume-role-with-web-identity \
               --role-arn "$ROLE_ARN" \
@@ -31,11 +39,6 @@ jobs:
             echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $BASH_ENV
             echo "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $BASH_ENV
             echo "export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" >> $BASH_ENV
-      - run:
-          name: Install Python, pip, and jq
-          command: |
-            sudo apt-get update
-            sudo apt-get install -y python3 python3-pip jq
       - run:
           name: Install Python dependencies
           command: |
